;; https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-11.html#%_sec_1.2

;; Exercise 1.9.
;; Each of the following two procedures defines a method
;; for adding two positive integers in terms of the procedures inc,
;; which increments its argument by 1,
;; and dec, which decrements its argument by 1.

;; Using the substitution model, illustrate the process
;; generated by each procedure in evaluating (+ 4 5).
;; Are these processes iterative or recursive?

(defn plus-1 [a b]
  (if (= a 0)
      b
      (inc (plus (dec a) b))))
;; plus-1
;; (plus-1 4 5)
;; + 1 (plus-1 3 5)
;; + 1 (+ 1 (plus-1 2 5))
;; + 1 (+ 1 (+ 1 (plus-1 1 5)))
;; + 1 (+ 1 (+ 1 (+ 1 (plus-1 0 5))))
;; + 1 (+ 1 (+ 1 (+ 1 5)))
;; + 1 (+ 1 (+ 1 6))
;; + 1 (+ 1 7)
;; + 1 8
;; 9

(defn plus-2 [a b]
  (if (= a 0)
      b
      (plus-2 (dec a) (inc b))))
;; (plus-2 4 5)
;; (plus-2 3 6)
;; (plus-2 2 7)
;; (plus-2 1 8)
;; (plus-2 0 9)
;; 9
