#lang sicp

#|
https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-11.html#%_sec_1.2
Exercise 1.9.  Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))
Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive? 
|#

(define (plus-1 a b)
  (if (= a 0)
      b
      (inc (plus-1 (dec a) b))))

(plus-1 3 2)

;; 3 2
;; 2 2
;; 1 2
;; 0 2
;; 0 3
;; 0 4
;; 0 5
;; 5 is returned

(define (plus-2 a b)
  (if (= a 0)
      b
      (plus-2 (dec a) (inc b))))

(plus-2 3 4)

;; 3 4
;; 2 5
;; 1 6
;; 0 7
;; 0 7
;; 0 7
;; 0 7
;; 7 is returned

;; both are recursive. 